name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

jobs:
### Windows ###
 ### Digital Twin Android E2E Tests, Multi configuration build (12 different test groups to cover) ###
- job: AndroidBuildDigitalTwin
  timeoutInMinutes: 45
  pool:
    name: Hosted VS2017
  displayName: Android Build - Digital Twin

  steps:
  - powershell: ./vsts/echo_versions.ps1
    displayName: 'Echo Versions'
    env:
      COMMIT_FROM: $(COMMIT_FROM)
    condition: always()

  - powershell: ./vsts/android_digitaltwin.cmd
    displayName: 'Android Build - Digital Twin'
    env:
      APPCENTER_DIGITAL_TWIN_APP_SECRET: $(APPCENTER-DIGITAL-TWIN-APP-SECRET)
      IOTHUB_CONNECTION_STRING: $(ANDROID-IOTHUB-CONNECTION-STRING)
      EVENT_HUB_CONNECTION_STRING: $(ANDROID-EVENT-HUB-CONNECTION-STRING)
    condition: always()

  - task: CopyFiles@2
    displayName: 'Copy Test Results to Artifact Staging Directory'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/digital-twin/e2e-tests/android/apk/build/outputs/apk'
      Contents: |
       *.*
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    continueOnError: true
    condition: always()

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'androidBuildFilesDigitalTwin'
      targetPath: 'digital-twin/e2e-tests/android/apk/build/outputs/apk'

- job: AndroidTestDigitalTwin
  timeoutInMinutes: 180
  pool:
    vmImage: 'macOS-latest'
  strategy:
    maxParallel: 12
    matrix:
      TestGroupDigitalTwin1:
        ANDROID_TEST_GROUP_ID: TestGroupDigitalTwin1

  displayName: Android Test  - Digital Twin
  dependsOn: AndroidBuildDigitalTwin
  steps:
  - powershell: ./vsts/install_appcenter_cli.ps1
    displayName: 'Install app center cli'
    condition: always()

  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: 'androidBuildFilesDigitalTwin'
      targetPath: $(Build.ArtifactStagingDirectory)/digital-twin/e2e-tests/android/apk/build/outputs/apk

  - task: AppCenterTest@1
    displayName: 'E2E with Visual Studio App Center'
    inputs:
      appFile: '$(Build.ArtifactStagingDirectory)/digital-twin/e2e-tests/android/apk/build/outputs/apk/debug/apk-debug.apk'
      frameworkOption: espresso
      espressoBuildDirectory: '$(Build.ArtifactStagingDirectory)/digital-twin/e2e-tests/android/apk/build/outputs/apk/androidTest/debug'
      serverEndpoint: 'AppCenter connection aziotclb'
      appSlug: 'Azure-Iot-Sdk/digital-twin-androide2e'
      devices: 'Azure-Iot-Sdk/api28_2'
      runOptions: '--test-parameter annotation=com.microsoft.azure.sdk.iot.digitaltwin.android.helper.$(ANDROID_TEST_GROUP_ID)'
      showDebugOutput: true